In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

Wikipedia article available here: https://en.wikipedia.org/wiki/List_of_deadly_earthquakes_since_1900

In [4]:
earthquakes = pd.read_csv('../data/earthquakes_wikitable.csv')
earthquakes

          Origin (UTC) Present-day country and link to Wikipedia article     Lat     Long Depth (km) Magnitude Secondary Effects  PDE Shaking Deaths  PDE Total Deaths  Utsu Total Deaths EM-DAT Total Deaths           Other Source Deaths
0     1900-05-11 17:23                                             Japan  38.700  141.100          5  7.0 MJMA               NaN                 NaN               NaN                NaN                 NaN                           NaN
1     1900-07-12 06:25                                            Turkey  40.300   43.100        NaN   5.9 Muk               NaN                 NaN               NaN              140.0                 NaN                           NaN
2     1900-10-29 09:11                                         Venezuela  11.000  -66.000          0    7.7 Mw               NaN                 NaN               NaN                NaN                 NaN                           NaN
3     1901-02-15 00:00                                             China  26.000  100.100          0    6.5 Ms               NaN                 NaN               NaN                NaN                 NaN                           NaN
4     1901-03-31 07:11                                          Bulgaria  43.400   28.700        NaN   6.4 Muk               NaN                 NaN               NaN                4.0                 NaN                           NaN
...                ...                                               ...     ...      ...        ...       ...               ...                 ...               ...                ...                 ...                           ...
1335  2011-03-24 20:25                 Burma (see 2011 Burma earthquake)     NaN      NaN        NaN    6.8 Mw               NaN                 NaN               NaN                NaN                 NaN                          150+
1336  2011-04-07 14:32          Japan (see April 2011 Miyagi earthquake)    38.2    140.0       66.0    7.1 Mw               NaN                 NaN               NaN                NaN                 NaN                           NaN
1337  2011-09-18 12:40                India (see 2011 Sikkim earthquake)  27.723   88.064       19.7    6.9 Mw                 L                 NaN               NaN                NaN                 NaN                          111+
1338  2011-09-23 10:41                  Turkey (see 2011 Van earthquake)    38.6     43.5        7.2    7.1 Mw               NaN                 NaN               NaN                NaN                 NaN  601 (as of October 30, 2011)
1339  2018-08-05 19:46                 Indonesia (see Lombok earthquake)     NaN      NaN       31.0    6.9 Mw               NaN                 NaN               NaN                NaN                 NaN                           NaN

[1340 rows x 12 columns]

In [5]:
# create a new column for magnitude that strips away seismic magnitude scales
earthquakes['Magnitude_Num'] = earthquakes['Magnitude'].str.extract('(^\d+.\d+)')
earthquakes['Magnitude_Num']

0       7.0
1       5.9
2       7.7
3       6.5
4       6.4
       ...
1335    6.8
1336    7.1
1337    6.9
1338    7.1
1339    6.9
Name: Magnitude_Num, Length: 1340, dtype: object

In [6]:
earthquakes.head()

       Origin (UTC) Present-day country and link to Wikipedia article     Lat     Long Depth (km) Magnitude Secondary Effects  PDE Shaking Deaths  PDE Total Deaths  Utsu Total Deaths EM-DAT Total Deaths Other Source Deaths Magnitude_Num
0  1900-05-11 17:23                                             Japan  38.700  141.100          5  7.0 MJMA               NaN                 NaN               NaN                NaN                 NaN                 NaN           7.0
1  1900-07-12 06:25                                            Turkey  40.300   43.100        NaN   5.9 Muk               NaN                 NaN               NaN              140.0                 NaN                 NaN           5.9
2  1900-10-29 09:11                                         Venezuela  11.000  -66.000          0    7.7 Mw               NaN                 NaN               NaN                NaN                 NaN                 NaN           7.7
3  1901-02-15 00:00                                             China  26.000  100.100          0    6.5 Ms               NaN                 NaN               NaN                NaN                 NaN                 NaN           6.5
4  1901-03-31 07:11                                          Bulgaria  43.400   28.700        NaN   6.4 Muk               NaN                 NaN               NaN                4.0                 NaN                 NaN           6.4

In [7]:
earthquakes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1340 entries, 0 to 1339
Data columns (total 13 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   Origin (UTC)                                       1340 non-null   object
 1   Present-day country and link to Wikipedia article  1340 non-null   object
 2   Lat                                                1325 non-null   object
 3   Long                                               1325 non-null   object
 4   Depth (km)                                         1250 non-null   object
 5   Magnitude                                          1339 non-null   object
 6   Secondary Effects                                  373 non-null    object
 7   PDE Shaking Deaths                                 738 non-null    float64
 8   PDE Total Deaths                                   749 non-null    float64
 9   Utsu Total Deaths                                  1027 non-null   float64
 10  EM-DAT Total Deaths                                559 non-null    object
 11  Other Source Deaths                                37 non-null     object
 12  Magnitude_Num                                      1338 non-null   object
dtypes: float64(3), object(10)
memory usage: 136.2+ KB

In [8]:
earthquakes['Magnitude_Num'] = pd.to_numeric(earthquakes['Magnitude_Num'])
earthquakes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1340 entries, 0 to 1339
Data columns (total 13 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   Origin (UTC)                                       1340 non-null   object
 1   Present-day country and link to Wikipedia article  1340 non-null   object
 2   Lat                                                1325 non-null   object
 3   Long                                               1325 non-null   object
 4   Depth (km)                                         1250 non-null   object
 5   Magnitude                                          1339 non-null   object
 6   Secondary Effects                                  373 non-null    object
 7   PDE Shaking Deaths                                 738 non-null    float64
 8   PDE Total Deaths                                   749 non-null    float64
 9   Utsu Total Deaths                                  1027 non-null   float64
 10  EM-DAT Total Deaths                                559 non-null    object
 11  Other Source Deaths                                37 non-null     object
 12  Magnitude_Num                                      1338 non-null   float64
dtypes: float64(4), object(9)
memory usage: 136.2+ KB